symfony:
  build: symfony/
  links:
    - redis
  volumes:
    - ./symfony/code:/var/www

nginx:
  build: nginx/
  ports:
    - 8080:80
  links:
    - fpm
  volumes_from:
    - symfony
  environment:
    <APP_SERVER_NAME>: dev-machine

fpm:
  build: php-fpm/
  links:
    - redis
  volumes_from:
    - symfony
  environment:
    APP_SERVER_NAME: dev-machine

redis:
  image: redis:latest
  ports:
    - 6379
